import { generateMeta } from '@/lib/seo';

export const metadata = generateMeta({
  title: 'Terms of Service',
  description: 'Terms and conditions for using ReplyGenie, the AI review response generator.',
  path: '/terms/',
});

export default function TermsPage() {
  return (
    <div className="container py-16 md:py-24 max-w-2xl mx-auto">
      <h1 className="text-3xl font-bold">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: February 9, 2026</p>

      <div className="mt-8 space-y-6 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">Acceptance of Terms</h2>
          <p>By using ReplyGenie (&ldquo;the Service&rdquo;), you agree to these Terms of Service. If you do not agree, please do not use the Service.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">Service Description</h2>
          <p>ReplyGenie is an AI-powered tool that generates suggested responses to customer reviews. The Service is provided for informational and productivity purposes. Generated responses are suggestions only — you are responsible for reviewing, editing, and posting any response on review platforms.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">Free and Paid Plans</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>The Free tier provides up to 3 responses per day at no cost.</li>
            <li>The Pro tier is billed monthly at the listed price via Stripe.</li>
            <li>You may cancel your Pro subscription at any time. Cancellation takes effect at the end of the current billing period.</li>
            <li>Refunds are available within 7 days of purchase for any reason.</li>
            <li>We reserve the right to modify pricing with 30 days&apos; notice to existing subscribers.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>Use the Service to generate responses that are defamatory, harassing, or illegal.</li>
            <li>Attempt to reverse-engineer, scrape, or exploit the Service.</li>
            <li>Circumvent usage limits through automation, multiple accounts, or other means.</li>
            <li>Use the Service to generate fake reviews or misleading content.</li>
            <li>Resell or redistribute generated responses as a competing service.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">AI-Generated Content Disclaimer</h2>
          <p>Responses generated by ReplyGenie are AI-created suggestions. While we strive for high quality, we make no guarantees about the accuracy, appropriateness, or effectiveness of any generated response. You are solely responsible for reviewing and approving any response before posting it publicly. We recommend editing generated responses to add personal details and verify accuracy.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">Intellectual Property</h2>
          <p>You own the responses generated using your input. ReplyGenie retains no rights to the responses you generate. The Service itself, including its design, code, and branding, is the property of ReplyGenie and protected by applicable intellectual property laws.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">Limitation of Liability</h2>
          <p>ReplyGenie is provided &ldquo;as is&rdquo; without warranty of any kind, express or implied. We are not liable for any damages arising from the use of the Service, including but not limited to: reputational damage from posted responses, loss of business, or any indirect, incidental, or consequential damages. Our total liability is limited to the amount you paid us in the 12 months preceding any claim.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">Service Availability</h2>
          <p>We strive for 99.9% uptime but do not guarantee uninterrupted access. We may modify, suspend, or discontinue features at any time. We will provide reasonable notice for material changes that affect paid subscribers.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">Changes to Terms</h2>
          <p>We may update these terms at any time. Material changes will be communicated via email to registered users. Continued use after changes constitutes acceptance.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-foreground mb-2">Contact</h2>
          <p>Questions about these terms? Contact us at <a href="mailto:support@replygenie.com" className="text-primary hover:underline">support@replygenie.com</a>.</p>
        </section>
      </div>
    </div>
  );
}
